project:
  type: website
  output-dir: docs

website:
  title: "Sreoshi's Data Visualization Portfolio"
  site-url: https://your-username.github.io/sreoshi-quarto-portfolio
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

execute:
  echo: true
  warning: false
  message: false
